function generateHistory(
  basePrice: number,
  days: number,
  volatility: number,
  trend: number
): { date: string; price: number }[] {
  const points: { date: string; price: number }[] = [];
  let price = basePrice * (1 - trend);

  for (let i = days; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    const noise = (Math.sin(i * 0.3) + Math.cos(i * 0.17)) * volatility;
    price = Math.max(
      basePrice * 0.5,
      price * (1 + trend / days + noise * 0.02)
    );
    points.push({
      date: date.toISOString().split("T")[0],
      price: Math.round(price * 100) / 100,
    });
  }

  return points;
}

function gradedHistory(
  basePrice: number,
  days: number,
  trend: number
): { date: string; price: number }[] {
  return generateHistory(basePrice, days, basePrice * 0.08, trend);
}

export const SEALED_PRODUCTS = [
  {
    id: "sealed-151-bb",
    category: "sealed" as const,
    name: "151 Booster Box",
    set: "Scarlet & Violet — 151",
    setCode: "MEW",
    type: "booster_box" as const,
    imageUrl: "https://images.pokemontcg.io/sv3pt5/logo.png",
    price: 289.99,
    currency: "EUR" as const,
    change24h: 1.2,
    change7d: 4.8,
    change30d: 12.3,
    history: generateHistory(289.99, 365, 15, 0.12),
    market: "EU" as const,
  },
  {
    id: "sealed-151-etb",
    category: "sealed" as const,
    name: "151 Elite Trainer Box",
    set: "Scarlet & Violet — 151",
    setCode: "MEW",
    type: "etb" as const,
    imageUrl: "https://images.pokemontcg.io/sv3pt5/logo.png",
    price: 74.5,
    currency: "EUR" as const,
    change24h: -0.5,
    change7d: 2.1,
    change30d: 8.7,
    history: generateHistory(74.5, 365, 4, 0.087),
    market: "EU" as const,
  },
  {
    id: "sealed-paldea-bb",
    category: "sealed" as const,
    name: "Paldea Evolved Booster Box",
    set: "Scarlet & Violet — Paldea Evolved",
    setCode: "PAL",
    type: "booster_box" as const,
    imageUrl: "https://images.pokemontcg.io/sv2/logo.png",
    price: 118.0,
    currency: "EUR" as const,
    change24h: 0.0,
    change7d: -1.4,
    change30d: -3.2,
    history: generateHistory(118, 365, 6, -0.032),
    market: "EU" as const,
  },
  {
    id: "sealed-obsidian-etb",
    category: "sealed" as const,
    name: "Obsidian Flames Elite Trainer Box",
    set: "Scarlet & Violet — Obsidian Flames",
    setCode: "OBF",
    type: "etb" as const,
    imageUrl: "https://images.pokemontcg.io/sv3/logo.png",
    price: 52.9,
    currency: "EUR" as const,
    change24h: 0.3,
    change7d: 1.8,
    change30d: 5.5,
    history: generateHistory(52.9, 365, 3, 0.055),
    market: "EU" as const,
  },
  {
    id: "sealed-crown-etb",
    category: "sealed" as const,
    name: "Crown Zenith Elite Trainer Box",
    set: "Sword & Shield — Crown Zenith",
    setCode: "CRZ",
    type: "etb" as const,
    imageUrl: "https://images.pokemontcg.io/swsh12pt5/logo.png",
    price: 89.0,
    currency: "EUR" as const,
    change24h: -0.8,
    change7d: 3.2,
    change30d: 15.6,
    history: generateHistory(89, 365, 5, 0.156),
    market: "EU" as const,
  },
  {
    id: "sealed-evolving-bb",
    category: "sealed" as const,
    name: "Evolving Skies Booster Box",
    set: "Sword & Shield — Evolving Skies",
    setCode: "EVS",
    type: "booster_box" as const,
    imageUrl: "https://images.pokemontcg.io/swsh7/logo.png",
    price: 620.0,
    currency: "EUR" as const,
    change24h: 2.1,
    change7d: 6.4,
    change30d: 9.8,
    history: generateHistory(620, 365, 25, 0.098),
    market: "EU" as const,
  },
  {
    id: "sealed-prismatic-bb",
    category: "sealed" as const,
    name: "Prismatic Evolutions Booster Box",
    set: "Scarlet & Violet — Prismatic Evolutions",
    setCode: "PRE",
    type: "booster_box" as const,
    price: 195.0,
    currency: "USD" as const,
    change24h: 3.5,
    change7d: 8.2,
    change30d: 22.1,
    history: generateHistory(195, 365, 12, 0.221),
    market: "US" as const,
  },
  {
    id: "sealed-surging-bb",
    category: "sealed" as const,
    name: "Surging Sparks Booster Box",
    set: "Scarlet & Violet — Surging Sparks",
    setCode: "SSP",
    type: "booster_box" as const,
    price: 142.0,
    currency: "USD" as const,
    change24h: -1.1,
    change7d: -2.3,
    change30d: 1.5,
    history: generateHistory(142, 365, 8, 0.015),
    market: "US" as const,
  },
];

export const GRADED_CARDS = [
  {
    id: "graded-charizard-151",
    category: "graded" as const,
    name: "Charizard ex",
    set: "Scarlet & Violet — 151",
    setCode: "MEW",
    cardNumber: "199/165",
    imageUrl: "https://images.pokemontcg.io/sv3pt5/199_hires.png",
    grades: [
      {
        company: "PSA" as const,
        grade: 10,
        price: 425.0,
        change24h: 1.5,
        change7d: 5.2,
        change30d: 18.4,
        history: gradedHistory(425, 365, 0.184),
      },
      {
        company: "PSA" as const,
        grade: 9,
        price: 185.0,
        change24h: 0.8,
        change7d: 3.1,
        change30d: 9.2,
        history: gradedHistory(185, 365, 0.092),
      },
      {
        company: "BGS" as const,
        grade: 10,
        price: 510.0,
        change24h: 2.0,
        change7d: 6.8,
        change30d: 21.0,
        history: gradedHistory(510, 365, 0.21),
      },
      {
        company: "CGC" as const,
        grade: 10,
        price: 340.0,
        change24h: 1.2,
        change7d: 4.5,
        change30d: 14.8,
        history: gradedHistory(340, 365, 0.148),
      },
    ],
    market: "EU" as const,
  },
  {
    id: "graded-pikachu-151",
    category: "graded" as const,
    name: "Pikachu",
    set: "Scarlet & Violet — 151",
    setCode: "MEW",
    cardNumber: "173/165",
    imageUrl: "https://images.pokemontcg.io/sv3pt5/173_hires.png",
    grades: [
      {
        company: "PSA" as const,
        grade: 10,
        price: 95.0,
        change24h: -0.5,
        change7d: 2.8,
        change30d: 11.5,
        history: gradedHistory(95, 365, 0.115),
      },
      {
        company: "PSA" as const,
        grade: 9,
        price: 42.0,
        change24h: 0.0,
        change7d: 1.5,
        change30d: 5.8,
        history: gradedHistory(42, 365, 0.058),
      },
    ],
    market: "EU" as const,
  },
  {
    id: "graded-umbreon-vmax",
    category: "graded" as const,
    name: "Umbreon VMAX (Alt Art)",
    set: "Sword & Shield — Evolving Skies",
    setCode: "EVS",
    cardNumber: "215/203",
    imageUrl: "https://images.pokemontcg.io/swsh7/215_hires.png",
    grades: [
      {
        company: "PSA" as const,
        grade: 10,
        price: 1850.0,
        change24h: 0.9,
        change7d: 4.1,
        change30d: 7.3,
        history: gradedHistory(1850, 365, 0.073),
      },
      {
        company: "BGS" as const,
        grade: 10,
        price: 2200.0,
        change24h: 1.1,
        change7d: 5.0,
        change30d: 8.5,
        history: gradedHistory(2200, 365, 0.085),
      },
      {
        company: "CGC" as const,
        grade: 10,
        price: 1450.0,
        change24h: 0.6,
        change7d: 3.8,
        change30d: 6.2,
        history: gradedHistory(1450, 365, 0.062),
      },
    ],
    market: "US" as const,
  },
  {
    id: "graded-giratina-vstar",
    category: "graded" as const,
    name: "Giratina VSTAR (Alt Art)",
    set: "Sword & Shield — Lost Origin",
    setCode: "LOR",
    cardNumber: "186/196",
    imageUrl: "https://images.pokemontcg.io/swsh11/186_hires.png",
    grades: [
      {
        company: "PSA" as const,
        grade: 10,
        price: 380.0,
        change24h: -1.2,
        change7d: -3.5,
        change30d: -8.2,
        history: gradedHistory(380, 365, -0.082),
      },
      {
        company: "PSA" as const,
        grade: 9,
        price: 165.0,
        change24h: -0.8,
        change7d: -2.1,
        change30d: -5.4,
        history: gradedHistory(165, 365, -0.054),
      },
    ],
    market: "EU" as const,
  },
  {
    id: "graded-lugia-v",
    category: "graded" as const,
    name: "Lugia V (Alt Art)",
    set: "Sword & Shield — Silver Tempest",
    setCode: "SIT",
    cardNumber: "186/195",
    imageUrl: "https://images.pokemontcg.io/swsh12/186_hires.png",
    grades: [
      {
        company: "PSA" as const,
        grade: 10,
        price: 520.0,
        change24h: 0.4,
        change7d: 2.9,
        change30d: 10.1,
        history: gradedHistory(520, 365, 0.101),
      },
      {
        company: "BGS" as const,
        grade: 9.5,
        price: 580.0,
        change24h: 0.7,
        change7d: 3.2,
        change30d: 11.8,
        history: gradedHistory(580, 365, 0.118),
      },
    ],
    market: "US" as const,
  },
  {
    id: "graded-mew-ex",
    category: "graded" as const,
    name: "Mew ex (Alt Art)",
    set: "Scarlet & Violet — 151",
    setCode: "MEW",
    cardNumber: "205/165",
    imageUrl: "https://images.pokemontcg.io/sv3pt5/205_hires.png",
    grades: [
      {
        company: "PSA" as const,
        grade: 10,
        price: 275.0,
        change24h: 2.3,
        change7d: 7.5,
        change30d: 19.8,
        history: gradedHistory(275, 365, 0.198),
      },
      {
        company: "CGC" as const,
        grade: 10,
        price: 210.0,
        change24h: 1.8,
        change7d: 6.2,
        change30d: 16.5,
        history: gradedHistory(210, 365, 0.165),
      },
    ],
    market: "EU" as const,
  },
];
