/** Prodotti monitorati — PSA JP + sealed ITA/ENG */

export const WATCHLIST_SEALED_EN = [
  {
    id: "sealed-151-bb-en",
    tcgplayerProductId: 593355,
    name: "151 Booster Box",
    set: "Scarlet & Violet — 151",
    setCode: "MEW",
    type: "booster_box" as const,
    language: "EN" as const,
    imageUrl: "https://assets.tcgdex.net/en/sv/sv03.5/logo",
  },
  {
    id: "sealed-151-etb-en",
    tcgplayerProductId: 528038,
    name: "151 Elite Trainer Box",
    set: "Scarlet & Violet — 151",
    setCode: "MEW",
    type: "etb" as const,
    language: "EN" as const,
    imageUrl: "https://assets.tcgdex.net/en/sv/sv03.5/logo",
  },
  {
    id: "sealed-prismatic-bb-en",
    tcgplayerProductId: 553001,
    name: "Prismatic Evolutions Booster Box",
    set: "Scarlet & Violet — Prismatic Evolutions",
    setCode: "PRE",
    type: "booster_box" as const,
    language: "EN" as const,
  },
  {
    id: "sealed-evolving-bb-en",
    tcgplayerProductId: 624679,
    name: "Evolving Skies Booster Box",
    set: "Sword & Shield — Evolving Skies",
    setCode: "EVS",
    type: "booster_box" as const,
    language: "EN" as const,
    imageUrl: "https://assets.tcgdex.net/en/swsh/swsh7/logo",
  },
  {
    id: "sealed-crown-etb-en",
    tcgplayerProductId: 450289,
    name: "Crown Zenith Elite Trainer Box",
    set: "Sword & Shield — Crown Zenith",
    setCode: "CRZ",
    type: "etb" as const,
    language: "EN" as const,
    imageUrl: "https://assets.tcgdex.net/en/swsh/swsh12.5/logo",
  },
];

/** Sealed ITA — prezzi Cardmarket (live richiede PkmnPrices Pro; fallback demo) */
export const WATCHLIST_SEALED_IT = [
  {
    id: "sealed-151-bb-it",
    name: "151 Display Booster (IT)",
    set: "Scarlet & Violet — 151",
    setCode: "MEW",
    type: "booster_box" as const,
    language: "IT" as const,
    imageUrl: "https://assets.tcgdex.net/en/sv/sv03.5/logo",
    cardmarketSlug: "Booster-Boxes/151",
    fallbackPriceEur: 295,
  },
  {
    id: "sealed-151-etb-it",
    name: "151 Elite Trainer Box (IT)",
    set: "Scarlet & Violet — 151",
    setCode: "MEW",
    type: "etb" as const,
    language: "IT" as const,
    imageUrl: "https://assets.tcgdex.net/en/sv/sv03.5/logo",
    cardmarketSlug: "Elite-Trainer-Boxes/151",
    fallbackPriceEur: 78,
  },
  {
    id: "sealed-prismatic-bb-it",
    name: "Prismatic Evolutions Booster Box (IT)",
    set: "Scarlet & Violet — Prismatic Evolutions",
    setCode: "PRE",
    type: "booster_box" as const,
    language: "IT" as const,
    cardmarketSlug: "Booster-Boxes/Prismatic-Evolutions",
    fallbackPriceEur: 182,
  },
  {
    id: "sealed-obsidian-etb-it",
    name: "Fiamme Obsidiane ETB (IT)",
    set: "Scarlet & Violet — Obsidian Flames",
    setCode: "OBF",
    type: "etb" as const,
    language: "IT" as const,
    imageUrl: "https://assets.tcgdex.net/en/sv/sv3/logo",
    cardmarketSlug: "Elite-Trainer-Boxes/Obsidian-Flames",
    fallbackPriceEur: 54,
  },
];

/** Carte PSA giapponesi — eBay sold live via PkmnPrices Pro; metadata via TCGdex */
export const WATCHLIST_PSA_JP = [
  {
    id: "graded-jp-pikachu-151",
    tcgdxCardId: "SV2a-173",
    name: "Pikachu",
    nameJa: "ピカチュウ",
    set: "ポケモンカード151",
    setCode: "SV2a",
    cardNumber: "173/165",
    imageUrl: "https://assets.tcgdex.net/ja/SV/SV2a/173",
    grades: [10, 9] as const,
    fallbackPsa10Eur: 120,
    fallbackPsa10Usd: 135,
  },
  {
    id: "graded-jp-mew-ex-151",
    tcgdxCardId: "SV2a-205",
    name: "Mew ex",
    nameJa: "ミュウex",
    set: "ポケモンカード151",
    setCode: "SV2a",
    cardNumber: "205/165",
    imageUrl: "https://assets.tcgdex.net/ja/SV/SV2a/205",
    grades: [10, 9] as const,
    fallbackPsa10Eur: 310,
    fallbackPsa10Usd: 340,
  },
  {
    id: "graded-jp-charizard-151",
    tcgdxCardId: "SV2a-201",
    name: "Charizard ex",
    nameJa: "リザードンex",
    set: "ポケモンカード151",
    setCode: "SV2a",
    cardNumber: "201/165",
    imageUrl: "https://assets.tcgdex.net/ja/SV/SV2a/201",
    grades: [10, 9] as const,
    fallbackPsa10Eur: 480,
    fallbackPsa10Usd: 520,
  },
  {
    id: "graded-jp-umbreon-vmax",
    tcgdxCardId: "S6a-025",
    name: "Umbreon VMAX (HR)",
    nameJa: "ブラッキーVMAX",
    set: "イーブイヒーローズ",
    setCode: "S6a",
    cardNumber: "025/069",
    imageUrl: "https://assets.tcgdex.net/ja/S/S6a/025",
    grades: [10] as const,
    fallbackPsa10Eur: 420,
    fallbackPsa10Usd: 465,
  },
  {
    id: "graded-jp-lillie",
    tcgdxCardId: "SM1M-066",
    name: "Lillie (SR)",
    nameJa: "リーリエ",
    set: "コレクション ムーン",
    setCode: "SM1M",
    cardNumber: "066/060",
    imageUrl: "https://assets.tcgdex.net/ja/SM/SM1M/066",
    grades: [10, 9] as const,
    fallbackPsa10Eur: 890,
    fallbackPsa10Usd: 950,
  },
  {
    id: "graded-jp-giratina-vstar",
    tcgdxCardId: "S12a-111",
    name: "Giratina VSTAR (AR)",
    nameJa: "ギラティナVSTAR",
    set: "VSTARユニバース",
    setCode: "S12a",
    cardNumber: "111/172",
    imageUrl: "https://assets.tcgdex.net/ja/S/S12a/111",
    grades: [10] as const,
    fallbackPsa10Eur: 195,
    fallbackPsa10Usd: 210,
  },
];
